def set_mock_env(monkeypatch):
    monkeypatch.setenv("APPLICATIONINSIGHTS_CONNECTION_STRING" , "myAPPLICATIONINSIGHTS_CONNECTION_STRING")
    monkeypatch.setenv("AZURE_MISTRALAI_ENDPOINT" , "myAZURE_MISTRALAI_ENDPOINT")
    monkeypatch.setenv("AZURE_MISTRALAI_KEY" , "myAZURE_MISTRALAI_KEY")
    monkeypatch.setenv("AZURE_MISTRALAI_TEMPERATURE" , "0")
    monkeypatch.setenv("AZURE_MISTRALAI_TOKENS" , "2000")
    monkeypatch.setenv("AZURE_MISTRALAI_MODEL" , "myAZURE_MISTRALAI_MODEL")
    monkeypatch.setenv("AZURE_OPENAI_API_VERSION" , "myAZURE_OPENAI_API_VERSION")
    monkeypatch.setenv("AZURE_OPENAI_COMPLETION_TOKENS" , "2000")
    monkeypatch.setenv("AZURE_OPENAI_COMPLETION_ENDPOINT" , "myAZURE_OPENAI_COMPLETION_ENDPOINT")
    monkeypatch.setenv("AZURE_OPENAI_COMPLETION_KEY" , "key")
    monkeypatch.setenv("AZURE_OPENAI_COMPLETION_TEMPERATURE" , "0")
    monkeypatch.setenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT_MODEL" , "myAZURE_OPENAI_EMBEDDING_DEPLOYMENT_MODEL")
    monkeypatch.setenv("AZURE_OPENAI_EMBEDDING_ENDPOINT" , "myAZURE_OPENAI_EMBEDDING_ENDPOINT")
    monkeypatch.setenv("AZURE_OPENAI_EMBEDDING_KEY" , "key")
    monkeypatch.setenv("AZURE_OPENAI_COMPLETION_DEPLOYMENT_MODEL" , "myAZURE_OPENAI_DEPLOYMENT_MODEL")
    monkeypatch.setenv("AZURE_SEARCH_API_VERSION" , "myAZURE_SEARCH_API_VERSION")
    monkeypatch.setenv("AZURE_SEARCH_ENDPOINT" , "myAZURE_SEARCH_ENDPOINT")
    monkeypatch.setenv("AZURE_SEARCH_INDEX" , "myAZURE_SEARCH_INDEX")
    monkeypatch.setenv("AZURE_SEARCH_INDEX_SEMANTIC_CONFIGURATION" , "myAZURE_SEARCH_INDEX_SEMANTIC_CONFIGURATION")
    monkeypatch.setenv("AZURE_SEARCH_K" , "0")
    monkeypatch.setenv("AZURE_SEARCH_SEARCH_METHOD" , "HYBRID")
    monkeypatch.setenv("AZURE_SEARCH_SEMANTIC_RANKING_ENABLED" , "True")
    monkeypatch.setenv("AZURE_SEARCH_TOP" , "0")
    monkeypatch.setenv("AZURE_SEARCH_KEY" , "myAZURE_SEARCH_KEY")
    monkeypatch.setenv("AZURE_SQL_CONNECTION_STRING" , "myConnectionString")
    monkeypatch.setenv("ENRICHMENT_ENDPOINT" , "myENRICHMENT_ENDPOINT")
    monkeypatch.setenv("QUERY_ENDPOINT" , "myQUERY_ENDPOINT")
    monkeypatch.setenv("CQA_ConfidenceThreshold" , "0.25")
    monkeypatch.setenv("CQA_DefaultNoResultAnswer" , "Nessuna risposta trovata")
    monkeypatch.setenv("CQA_Deployment" , "myCQA_Deployment")
    monkeypatch.setenv("CQA_Endpoint" , "myCQA_Endpoint")
    monkeypatch.setenv("CQA_KeyCredential" , "myCQA_KeyCredential")
    monkeypatch.setenv("CQA_KnowledgeBaseProject" , "myCQA_KnowledgeBaseProject")
    monkeypatch.setenv("CQA_KnowledgeBaseProjectDCO" , "auu-faq")
    monkeypatch.setenv("CQA_TagsDCO" , "auu")
    monkeypatch.setenv('STORAGE_ACCOUNT_KEY', 'key')
    monkeypatch.setenv('STORAGE_ACCOUNT_NAME', 'name')
    monkeypatch.setenv('STORAGE_BULK_SPLIT_FILES_CONTAINER', 'container')
    monkeypatch.setenv('STORAGE_DATA_SOURCE_SPLIT_FILES_CONTAINER', 'container')
    monkeypatch.setenv('STORAGE_CONNECTION_STRING', 'connection_string')
    monkeypatch.setenv('STORAGE_PROMPT_FILES_CONTAINER', 'container')
    monkeypatch.setenv('STORAGE_UPLOADED_FILES_CONTAINER', 'container')
    monkeypatch.setenv('STORAGE_UPLOADED_SPLIT_FILES_CONTAINER', 'container')
    monkeypatch.setenv('PROMPT_ANSWER_GENERATION_MARKDOWN_ENABLED', 'False')